show an error message when failing to create the fifo

diff --git a/bkykeepfifo b/bkykeepfifo
--- a/bkykeepfifo
+++ b/bkykeepfifo
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 # Keep the fifo being opened several hours.
 
 fifo=/tmp/bky-led-fifo
@@ -7,7 +7,11 @@ fifo=/tmp/bky-led-fifo
 if [ ! -p "$fifo" ]; then
   mkfifo "$fifo"
 fi
+if [ ! -p "$fifo" ]; then
+  echo "Error: cannot create a fifo '$fifo'" 1>&2
+  exit 1
+fi
 
 # Keep the fifo being opened.
 sleep 30000 >"$fifo" &
-echo "A background process (pid=$!) has been launched."
+echo "Success: a background process (pid=$!) has been launched."
